version: '2'
services:
  mariadb:
    container_name: mariadb
    image: docker.io/bitnami/mariadb:10.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=magento
      - MARIADB_DATABASE=magento_db
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    container_name: magento2
    image: docker.io/bitnami/magento:2
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=magento
      - MAGENTO_DATABASE_NAME=magento_db
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
  phpmyadmin:
       container_name: phpmyadmin
       restart: always
       image: phpmyadmin/phpmyadmin:latest
       environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_USER=magento
         - PMA_HOST=mariadb
         - PMA_PORT=3306
       ports:
         - "8080:80"
       links:
         - mariadb:magento_db
       depends_on:
         - mariadb
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local